name: 02 - Workflow Events
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the triggering event
        run: echo "The triggering event is ${{ toJson(github.event) }}"
      - name: show the triggering event name
        run: echo "The triggering event name is ${{ github.event_name }}"
      - name: show the triggering event type
        run: echo "The triggering event type is ${{ github.event.action }}"