name: 02 - Workflow Events
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the triggering event
        run: echo "The triggering event is ${{ toJson(github.event) }}"
      - name: show the triggering event name
        run: echo "The triggering event name is ${{ github.event_name }}"
      - name: show the triger actor
        run: echo "The triggering actor is ${{ github.actor }}"
      - name: show the repository name
        run: echo "The repository name is ${{ github.repository }}"